export const RECEIVE_USER_DATA = 'RECEIVE_USER_DATA';
export const RECEIVE_SEARCH_DATA = 'RECEIVE_SEARCH_DATA';
export const SELECTED_BOOK = 'SELECTED_BOOK';
export const BY_USER_PREFERENCE = 'BY_USER_PREFERENCE';
